export const actionTypes = {
  GET_NAVBAR_STRUCTURE_REQUESTED: 'GET_NAVBAR_STRUCTURE_REQUESTED',
  GET_NAVBAR_STRUCTURE_COMPLETED: 'GET_NAVBAR_STRUCTURE_COMPLETED',
  SECTION_CHANGED: 'SECTION_CHANGED'
}
