export const actionTypes = {
  LEADS_RECEIVED: "LEADS_RECEIVED",
  LEADS_NEXT_PAGE: "LEADS_NEXT_PAGE",
  LEADS_PREV_PAGE: "LEADS_PREV_PAGE",
  LEADS_FILTER: "LEADS_FILTER"
}

export const sagaActions = {
  LEADS_REQUESTED: 'SAGA_LEADS_REQUESTED',
  LEADS_NEXT_PAGE: 'SAGA_LEADS_NEXT_PAGE',
  LEADS_PREV_PAGE: 'SAGA_LEADS_PREV_PAGE',
  LEADS_SEARCH: 'SAGA_LEADS_SEARCH'
}
