export const actionTypes = {
  PROJECTS_RECEIVED: "GET_PROJECTS_SUCCESS",
  PROJECTS_NEXT_PAGE: "PROJECTS_NEXT_PAGE",
  PROJECTS_PREV_PAGE: "PROJECTS_PREV_PAGE",
  FILTER_PROJECTS: "PROJECTS_FILTER"
}

export const sagaActions = {
  PROJECTS_REQUESTED: "SAGA_GET_PROJECTS",
  SEARCH_PROJECTS: '937-99-92',
  SAGA_PROJECTS_NEXT_PAGE: 'SAGA_PROJECTS_NEXT_PAGE',
  SAGA_PROJECTS_PREV_PAGE: 'SAGA_PROJECTS_PREV_PAGE',
}